/**
 * Este script en Node.js:
 * 1. Lee y parsea el fichero channels.xml con la ayuda de xml2js.
 * 2. Para cada <channels_group> obtenido del XML, hace una petición HTTP/HTTPS 
 *    a la URI indicada para obtener una lista .m3u.
 * 3. Parseando la lista M3U, extrae los nombres de cada canal (línea #EXTINF)
 *    y la URL (la línea inmediatamente siguiente).
 * 4. Genera un CSV con las columnas:
 *    <idioma>,<categoria>,<nombre>,<url>,<content_type>
 * 5. Por defecto se guardará en un fichero 'output.csv'.
 *
 * Requisitos:
 *   - npm install xml2js axios
 */

const fs = require('fs');
const xml2js = require('xml2js');
const axios = require('axios');
const https = require('https');
const http = require('http');
const m3u8Parser = require('m3u8-parser');
//const { errorCodes } = require('./index');

const errorCodes = [
  "400",
  "401",
  "402",
  "403",
  "404",
  "405",
  "406",
  "407",
  "408",
  "409",
  "410",
  "411",
  "412",
  "413",
  "414",
  "415",
  "416",
  "417",
  "418",
  "419",
  "420",
  "421",
  "422",
  "423",
  "424",
  "425",
  "426",
  "427",
  "428",
  "429",
  "431",
  "451",
  "500",
  "501",
  "502",
  "503",
  "504",
  "505",
  "506",
  "507",
  "508",
  "509",
  "510",
  "511",
  "520",
];

const playlists = [
  // Aquí se podrían añadir URIs adicionales si fuera necesario
  "./public/assets/01.m3u8",
  "./public/assets/1000.m3u8",
  "./public/assets/1728.m3u8",
  "./public/assets/193.m3u8",
  "./public/assets/1music.m3u8",
  "./public/assets/2000.m3u8",
  "./public/assets/206849c7acd1570962df1ad525fa8688.m3u8",
  "./public/assets/24h_main_dvr.m3u8",
  "./public/assets/2600000.m3u8",
  "./public/assets/2.m3u8",
  "./public/assets/3SDdwqdV.m3u8",
  "./public/assets/470906932351128240316939.m3u8",
  "./public/assets/47561_264_live.m3u8",
  "./public/assets/48519_264_live.m3u8",
  "./public/assets/540.m3u8",
  "./public/assets/5473142.m3u8",
  "./public/assets/720.m3u8",
  "./public/assets/almamlka_1080p.m3u8",
  "./public/assets/a.m3u8",
  "./public/assets/aragontv_canal1.m3u8",
  "./public/assets/at5_high.m3u8",
  "./public/assets/bakutv_720p.m3u8",
  "./public/assets/balatontv.m3u8",
  "./public/assets/bonceswa.m3u8",
  "./public/assets/chile.m3u8",
  "./public/assets/chunklist_b1064000.m3u8",
  "./public/assets/chunklist_b1431072.m3u8",
  "./public/assets/chunklist_b2328000_DVR.m3u8",
  "./public/assets/chunklist_b3128000.m3u8",
  "./public/assets/chunklist.m3u8",
  "./public/assets/chunklist_w1062911391.m3u8",
  "./public/assets/chunklist_w1097511114.m3u8",
  "./public/assets/chunklist_w1203497461.m3u8",
  "./public/assets/chunklist_w1227324980.m3u8",
  "./public/assets/chunklist_w1300032347.m3u8",
  "./public/assets/chunklist_w1379656191.m3u8",
  "./public/assets/chunklist_w1811501290.m3u8",
  "./public/assets/chunklist_w1898633944.m3u8",
  "./public/assets/chunklist_w190750142.m3u8",
  "./public/assets/chunklist_w259077935.m3u8",
  "./public/assets/chunklist_w470534363.m3u8",
  "./public/assets/chunklist_w574389438.m3u8",
  "./public/assets/chunklist_w697757887.m3u8",
  "./public/assets/chunklist_w788671625.m3u8",
  "./public/assets/chunklist_w823540263.m3u8",
  "./public/assets/chunklist_w954408022_b1548000_sleng.m3u8",
  "./public/assets/chunklist_w980140357.m3u8",
  "./public/assets/chunks.m3u8",
  "./public/assets/etv2.m3u8",
  "./public/assets/etv.m3u8",
  "./public/assets/f941a1259615aa91505e37fe249fea5c.m3u8",
  "./public/assets/f.m3u8",
  "./public/assets/gtv_03.m3u8",
  "./public/assets/hk2.m3u8",
  "./public/assets/ibgrlive.m3u8",
  "./public/assets/index_1.m3u8",
  "./public/assets/index.m3u8",
  "./public/assets/interracial.m3u8",
  "./public/assets/jordanhd_1080p.m3u8",
  "./public/assets/la1_main.m3u8",
  "./public/assets/la2_main.m3u8",
  "./public/assets/live.m3u8",
  "./public/assets/livestream.m3u8",
  "./public/assets/malive_high.m3u8",
  "./public/assets/manifest.m3u8",
  "./public/assets/master_540.m3u8",
  "./public/assets/master.m3u8",
  "./public/assets/master_v720.m3u8",
  "./public/assets/mono.m3u8",
  "./public/assets/music.m3u8",
  "./public/assets/my999.m3u8",
  "./public/assets/nodrm.m3u8",
  "./public/assets/ntk.m3u8",
  "./public/assets/onetv.m3u8",
  "./public/assets/pc.m3u8",
  "./public/assets/pequetv.m3u8",
  "./public/assets/player.m3u8",
  "./public/assets/playlist720_p.m3u8",
  "./public/assets/playlist720p.m3u8",
  "./public/assets/playlist_high.m3u8",
  "./public/assets/playlist.m3u8",
  "./public/assets/pl.m3u8",
  "./public/assets/prog_index.m3u8",
  "./public/assets/puc9djrh2cg7wjqw8v9was5fu5kh4a.m3u8",
  "./public/assets/QmusicNL.m3u8",
  "./public/assets/radio350.m3u8",
  "./public/assets/redtv_multi.m3u8",
  "./public/assets/rmtv.m3u8",
  "./public/assets/rtvnp.m3u8",
  "./public/assets/skate_phantom_flex_4k.m3u8",
  "./public/assets/smash.m3u8",
  "./public/assets/sna_720.m3u8",
  "./public/assets/sotv1_high.m3u8",
  "./public/assets/star1lowhd.m3u8",
  "./public/assets/star1mediumhd.m3u8",
  "./public/assets/stream_0.m3u8",
  "./public/assets/stream.m3u8",
  "./public/assets/tiszatv_1.m3u8",
  "./public/assets/tv24_480p.m3u8",
  "./public/assets/tvcityub.m3u8",
  "./public/assets/tv.m3u8",
  "./public/assets/tvt.m3u8",
  "./public/assets/valkenburg.m3u8",
  "./public/assets/web101tv.m3u8",
  "./public/assets/wzra.m3u8",
  "./public/assets/zwtv.m3u8",
];

export async function loadM3U() {

  // 1. Leemos el contenido del fichero channels.xml
  let xmlData = '';
  let csvLines = [];
  let languages = [
    "ad",
"ae",
"af",
"ag",
"ai",
"al",
"am",
"an",
"ao",
"aq",
"ar",
"as",
"at",
"au",
"aw",
"az",
"ba",
"bb",
"bd",
"be",
"bf",
"bg",
"bh",
"bi",
"bj",
"bm",
"bn",
"bo",
"br",
"bs",
"bt",
"bv",
"bw",
"by",
"bz",
"ca",
"cc",
"cd",
"cf",
"cg",
"ch",
"ci",
"ck",
"cl",
"cm",
"cn",
"co",
"cr",
"cs",
"cu",
"cv",
"cx",
"cy",
"cz",
"de",
"dj",
"dk",
"dm",
"do",
"dz",
"ec",
"ee",
"eg",
"eh",
"er",
"es",
"et",
"fi",
"fj",
"fk",
"fm",
"fo",
"fr",
"ga",
"gb",
"gd",
"ge",
"gf",
"gh",
"gi",
"gl",
"gm",
"gn",
"gp",
"gq",
"gr",
"gs",
"gt",
"gu",
"gw",
"gy",
"hk",
"hm",
"hn",
"hr",
"ht",
"hu",
"id",
"ie",
"il",
"in",
"io",
"iq",
"ir",
"is",
"it",
"jm",
"jo",
"jp",
"ke",
"kg",
"kh",
"ki",
"km",
"kn",
"kp",
"kr",
"kw",
"ky",
"kz",
"la",
"lb",
"lc",
"li",
"lk",
"lr",
"ls",
"lt",
"lu",
"lv",
"ly",
"ma",
"mc",
"md",
"mg",
"mh",
"mk",
"ml",
"mm",
"mn",
"mo",
"mp",
"mq",
"mr",
"ms",
"mt",
"mu",
"mv",
"mw",
"mx",
"my",
"mz",
"na",
"nc",
"ne",
"nf",
"ng",
"ni",
"nl",
"no",
"np",
"nr",
"nu",
"nz",
"om",
"pa",
"pe",
"pf",
"pg",
"ph",
"pk",
"pl",
"pm",
"pn",
"pr",
"ps",
"pt",
"pw",
"py",
"qa",
"re",
"ro",
"rs",
"ru",
"rw",
"sa",
"sb",
"sc",
"sd",
"se",
"sg",
"sh",
"si",
"sj",
"sk",
"sl",
"sm",
"sn",
"so",
"sr",
"st",
"sv",
"sy",
"sz",
"tc",
"td",
"tf",
"tg",
"th",
"tj",
"tk",
"tl",
"tm",
"tn",
"to",
"tr",
"tt",
"tv",
"tw",
"tz",
"ua",
"ug",
"um",
"us",
"uy",
"uz",
"va",
"vc",
"ve",
"vg",
"vi",
"vn",
"vu",
"wf",
"ws",
"ye",
"yt",
"za",
"zm",
"zw"
  ];

  let types = [1, 2, 3, 4, 5];

  for (let u = 0; u < languages.length; u++) {
    let lang = languages[u];
    let countryName = { name: '', code: '' };
    for (let i = 0; i < types.length; i++) {
      let type = types[i];
      let uri = './public/assets/' + lang + '_' + type + '.m3u';

      let m3uFile = await fs.readFileSync(uri, 'utf8');
      const parser = new m3u8Parser.Parser();
      parser.push(m3uFile);
      parser.end();
      const parsedM3U = parser.manifest;
      let segments = parsedM3U.segments;

      for (let j = 0; j < segments.length; j++) {
        let segment = segments[j];

        let title = segment.title;
        let url = segment.uri;
        let statusCode = 200;
        let contentType;
        let category;
        if (type == 1) {
          category = 'Web TV';
          contentType = 'video/m3u';
        } else if (type == 2) {
          category = 'Web Radio';
          contentType = 'audio';
        } else if (type == 3) {
          category = 'Web Cam';
          contentType = 'video';
        } else if (type == 4) {
          category = 'Web Programmes';
          contentType = 'video';
        }
        let csvLine = lang + ',' + category + ',' + title + ',' + url + ',' + contentType + ',' + statusCode;
        //console.log('line', line);
        //add the line to the csvLines
        csvLines.push(csvLine);
      }
    }
  }
  // Generamos el contenido CSV final, separando las líneas por salto de línea
  //let csvContent = csvLines.join('\n');


  console.log('csvLines', csvLines);

  return await csvLines;
}

export default loadM3U;