<?xml version="1.0" encoding="UTF-8"?>
<wslfe:webstream_link_exchange xmlns:wslfe="http://database.freetuxtv.net/wslfe">
	<wslfe:sequence source="freetuxtv_database">
		<wslfe:stream name="1 TV">https://tv.cdn.xsg.ge/gpb-1tv/index.m3u8</wslfe:stream>
		<wslfe:stream name="101TV Malaga">https://limited38.todostreaming.es/live/101tv-web101tv.m3u8</wslfe:stream>
		<wslfe:stream name="1Music Hungary">http://1music.hu/1music.m3u8</wslfe:stream>
		<wslfe:stream name="2 TV">https://tv.cdn.xsg.ge/gpb-2tv/index.m3u8</wslfe:stream>
		<wslfe:stream name="24 TV">https://turkmedya-live.ercdn.net/tv24/tv24_480p.m3u8</wslfe:stream>
		<wslfe:stream name="24h">https://rtvelivestreamv3.akamaized.net/24h/24h_main_dvr.m3u8</wslfe:stream>
		<wslfe:stream name="24h Canarias">https://ztnr.rtve.es/ztnr/5473142.m3u8</wslfe:stream>
		<wslfe:stream name="30A TV">https://30a-tv.com/my999.m3u8</wslfe:stream>
		<wslfe:stream name="30A TV MUSIC">https://30a-tv.com/music.m3u8</wslfe:stream>
		<wslfe:stream name="4E TV">http://eu2.tv4e.gr:554/live/smil:myStream.sdp.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="4Fun TV">https://stream.4fun.tv:8888/hls/4f_high/index.m3u8</wslfe:stream>
		<wslfe:stream name="7kanal-odessa">https://cdn10.live-tv.cloud/7tvod/7tvod-abr-lq/7tvod/7tvod-sub/chunks.m3u8</wslfe:stream>
		<wslfe:stream name="8 TV (RU)">https://v4.proofix.ru/8tv-europe/tracks-v1a1/mono.m3u8</wslfe:stream>
		<wslfe:stream name="a7TV">https://play.streamkit.tv/content/channel/aseventv/live/aseventv.player.m3u8</wslfe:stream>
		<wslfe:stream name="Abu Dhabi TV">https://admdn2ta.cdn.mangomolo.com/adtv/smil:adtv.stream.smil/chunklist.m3u8</wslfe:stream>
		<wslfe:stream name="Action 24 Greece HD">http://dai.ly/x61fbhs</wslfe:stream>
		<wslfe:stream name="Ajyal tv">http://htvajyal.mada.ps:8888/ajyal/tracks-v1a1/mono.m3u8</wslfe:stream>
		<wslfe:stream name="Al Jazeera Arabic Qatar QA">https://live-hls-web-aja.getaj.net/AJA/index.m3u8</wslfe:stream>
		<wslfe:stream name="Al Jazeera Balkans (1080p)">https://live-hls-web-ajb.getaj.net/AJB/index.m3u8</wslfe:stream>
		<wslfe:stream name="Al Jazeera Live">https://live-hls-web-aje.getaj.net/AJE/index.m3u8</wslfe:stream>
		<wslfe:stream name="Alcarria TV">https://cls.alcarria.tv/live/alcarriatv-livestream.m3u8</wslfe:stream>
		<wslfe:stream name="Aleph News">https://stream-aleph.m.ro/Aleph/ngrp:Alephnewsmain.stream_all/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Aljazeera HD">https://live-hls-web-aja.getaj.net/AJA/01.m3u8</wslfe:stream>
		<wslfe:stream name="AlmamlkaTV HD">https://almamlka-live.ercdn.net/almamlka/almamlka_1080p.m3u8</wslfe:stream>
		<wslfe:stream name="Alsharqiya Tv">rtmp://ns8.indexforce.com/alsharqiyalive/mystream</wslfe:stream>
		<wslfe:stream name="Alsharqiya Tv">rtmp://ns8.indexforce.com/home/mystream</wslfe:stream>
		<wslfe:stream name="ALTV">https://thaipbs-ujxrch.cdn.byteark.com/live/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Alvin_Channel.tv">http://cdn10-alvinchannel.yayin.com.tr/alvinchannel/alvinchannel/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Angel TV America">https://cdn3.wowza.com/5/TDJ0aWNkNXFxWWta/angeltvcloud/ngrp:angelamerica_all/chunklist_b1431072.m3u8</wslfe:stream>
		<wslfe:stream name="ANN news">https://youtu.be/coYw-eVU0Ks</wslfe:stream>
		<wslfe:stream name="Aragon TV">https://cartv.streaming.aranova.es/hls/live/aragontv_canal1.m3u8</wslfe:stream>
		<wslfe:stream name="Arirang">https://amdlive-ch01-ctnd-com.akamaized.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="ARTE HD">https://artesimulcast.akamaized.net/hls/live/2030993/artelive_de/master_v720.m3u8</wslfe:stream>
		<wslfe:stream name="asianet news">https://vidcdn.vidgyor.com/asianet-origin/liveabr/asianet-origin/live2/chunks.m3u8</wslfe:stream>
		<wslfe:stream name="ATV">http://streamservers.atv.hu/atvlive/atvstream_1_aac/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="AUTO BILD TV">https://auto-bild.personalstream.tv/v1/bildde/master.m3u8</wslfe:stream>
		<wslfe:stream name="Auto Moto TV">http://100automoto.tv:1935/bgtv1/Stream1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="automoto/tv">http://100automoto.tv:1935/bgtv1/autotv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="AYV">https://1219373429.rsc.cdn77.org/live/stream-1/chunklist.m3u8</wslfe:stream>
		<wslfe:stream name="Azerbaijan_News.tv">https://edge1.socialsmart.tv/aznews/smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="baden tv sued">https://cdn.icu.de/rtplive/smil:btvsued.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="baden-tv">http://cdn.icu.de/rtplive/btv.stream/chunklist_w574389438.m3u8</wslfe:stream>
		<wslfe:stream name="baku.tv">https://rtmp.baku.tv/live/bakutv_720p.m3u8</wslfe:stream>
		<wslfe:stream name="Balaton TV">https://stream.iptvservice.eu/hls/balatontv.m3u8</wslfe:stream>
		<wslfe:stream name="balkanweb.com/news24">https://tv.balkanweb.com/news24/livestream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Banat TV">https://www.btv.ro/hls/banat-tv.m3u8</wslfe:stream>
		<wslfe:stream name="Banovina TV">rtmp://video.radio-banovina.hr/live/myStream</wslfe:stream>
		<wslfe:stream name="baraza tv greek music 3">https://eco.streams.ovh/BarazaTV/BarazarazaTV/BarazaTV/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="barazatv hd">https://eco.streams.ovh:443/BarazaTV/BarazaTV/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="barazatv hd dance &amp; pop music">https://video1.getstreamhosting.com:1936/8490/8490/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="bbc.com/news/world">http://103.199.161.254/Content/bbcworld/Live/Channel(BBCworld)/Stream(01)/index.m3u8</wslfe:stream>
		<wslfe:stream name="Bip TV">https://biptv.tv/live/biptvstream_orig/index.m3u8</wslfe:stream>
		<wslfe:stream name="BLK Regional TV">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mp4:BLKonline_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="bnptv">mms://bnptv.info:10801/</wslfe:stream>
		<wslfe:stream name="Bonce TV">https://seswa.bonce.tv/hls/bonceswa.m3u8</wslfe:stream>
		<wslfe:stream name="BR Fernsehen Nord HD">https://mcdn.br.de/br/fs/bfs_nord/hls/de/master.m3u8</wslfe:stream>
		<wslfe:stream name="BR Fernsehen Süd HD">https://mcdn.br.de/br/fs/bfs_sued/hls/de/master.m3u8</wslfe:stream>
		<wslfe:stream name="BritAsia TV">https://dai.ly/x6s18p8</wslfe:stream>
		<wslfe:stream name="Bucovina TV">http://46.4.14.12:9999/btvsvlive/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Budakalasz">https://stream.streaming4u.hu/TVBudakalasz/tracks-v1a1/mono.m3u8</wslfe:stream>
		<wslfe:stream name="Bulgaria on air">http://lb-hls.cdn.bg/2006/fls/bonair.stream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="BX1">https://59959724487e3.streamlock.net/stream/live/chunklist_w1203497461.m3u8</wslfe:stream>
		<wslfe:stream name="Canal 10 Chetumal [Mexico]">https://canal10.mediaflix.istream.mx/wza_live/live/movil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Canalcosta TV">https://5d8d85cf2c308.streamlock.net:1936/CanalcostaTV/WXP6YT/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Canale 7 [ITALY]">http://wms.shared.streamshow.it:1935/canale7/canale7/live.m3u8?IPTVCOTIA</wslfe:stream>
		<wslfe:stream name="CATVE HD">http://wowza4.catve.com.br:1935/live/livestream/playlist.m3u8?CANAISGLAU</wslfe:stream>
		<wslfe:stream name="Catve HD">http://wowza4.catve.com.br:1935/live/livestream/playlist.m3u8?IPTVCOTIA++++</wslfe:stream>
		<wslfe:stream name="CBN NEWS">https://bcovlive-a.akamaihd.net/re8d9f611ee4a490a9bb59e52db91414d/us-east-1/734546207001/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="CGTN Français">https://news.cgtn.com/resource/live/french/cgtn-f.m3u8</wslfe:stream>
		<wslfe:stream name="ch4teen clip">http://ch14.tv/live/ch4teenclip/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Ch4teen Documentary">http://ch14.tv/live/ch4teendoc/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="ch4teen kids">http://ch14.tv/live/ch4teenkids/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="ch4teen quran">http://ch14.tv/live/ch4teenquran/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="ch4teen1">http://ch14.tv/live/ch4teen1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Chaula TV">https://video.chaula.tv/hls/live/high/playlist_high.m3u8</wslfe:stream>
		<wslfe:stream name="Chaula TV Rīga">https://video.chaula.tv/hls/live/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Chaula TV Rīga">http://video.chaula.tv/hls/live/high/playlist_high.m3u8</wslfe:stream>
		<wslfe:stream name="city.bg/tv">https://tv.city.bg/play/tshls/citytv/2.m3u8</wslfe:stream>
		<wslfe:stream name="clubbingtv.com">https://clubbingtv-rakuten.amagi.tv/playlist720_p.m3u8</wslfe:stream>
		<wslfe:stream name="CNA SAT TV">rtmp://str81.creacast.com:80/cna/live.sdp</wslfe:stream>
		<wslfe:stream name="cna tv">https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index.m3u8</wslfe:stream>
		<wslfe:stream name="Da Nang TV2">http://drtdnglive.e49a7c38.cdnviet.com/livestream/chunklist.m3u8</wslfe:stream>
		<wslfe:stream name="Das Erste HD">https://mcdn.daserste.de/daserste/de/master.m3u8</wslfe:stream>
		<wslfe:stream name="Das Wort TV">https://stream.daswort.tv/master.m3u8</wslfe:stream>
		<wslfe:stream name="DASDING-VisualRadio">https://swrdasdingvr-hls.akamaized.net/hls/live/2018681/dasdingvr/master.m3u8</wslfe:stream>
		<wslfe:stream name="dbm-tv.fr">http://dbmtv.vedge.infomaniak.com/livecast/dbmtv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="DDD">https://cdn.adultiptv.net/interracial.m3u8</wslfe:stream>
		<wslfe:stream name="deejay.it/tv">https://streamcdnb4-4c4b867c89244861ac216426883d1ad0.msvdn.net/live/S85984808/sMO0tz9Sr2Rk/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="demo">http://sample.vodobox.net/skate_phantom_flex_4k/skate_phantom_flex_4k.m3u8</wslfe:stream>
		<wslfe:stream name="Deutsche Welle">https://dwamdstream111.akamaized.net/hls/live/2017972/dwstream111/index.m3u8</wslfe:stream>
		<wslfe:stream name="Deutsche Welle+">https://dwamdstream110.akamaized.net/hls/live/2017971/dwstream110/index.m3u8</wslfe:stream>
		<wslfe:stream name="Die Neue Zeit TV">https://www.onairport.live/die-neue-zeit-tv-live/livestream_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="dorf tv (Oberösterreich)">https://stream.openplayout.org/hls/dorf_high/index.m3u8</wslfe:stream>
		<wslfe:stream name="DW-TV English">https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8</wslfe:stream>
		<wslfe:stream name="DW-TV Español">https://dwamdstream104.akamaized.net/hls/live/2015530/dwstream104/index.m3u8</wslfe:stream>
		<wslfe:stream name="EBS KIDS">https://ebsonair.ebs.co.kr/ebsufamilypc/familypc1m/chunklist_w1898633944.m3u8</wslfe:stream>
		<wslfe:stream name="EbS Live (Europe by Satellite)">https://euc-live.fl.freecaster.net/live/eucom/ebs-audio_int=96000-video=2600000.m3u8</wslfe:stream>
		<wslfe:stream name="EbS+ Live (Europe by Satellite)">https://euc-live.fl.freecaster.net/live/eucom/ebsp-audio_int=96000-video=2600000.m3u8</wslfe:stream>
		<wslfe:stream name="EDGEsport.uk">https://edgesports-sportstribal.amagi.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="edition.cnn">https://cnn-cnninternational-1-eu.rakuten.wurl.tv/206849c7acd1570962df1ad525fa8688.m3u8</wslfe:stream>
		<wslfe:stream name="EL.tv">http://85.132.53.162:1935/live/eltv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Elektrika">https://rtmp.elektrika.cz/live/myStream.sdp/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Elektrika TV">rtmp://rtmp.elektrika.cz/live/myStream.sdp</wslfe:stream>
		<wslfe:stream name="ETV">https://sb.err.ee/live/etv.m3u8</wslfe:stream>
		<wslfe:stream name="ETV Ⓖ">http://sb.err.ee/live/etv.m3u8</wslfe:stream>
		<wslfe:stream name="ETV2 Ⓖ">http://sb.err.ee/live/etv2.m3u8</wslfe:stream>
		<wslfe:stream name="Euronews Espanol">https://dai.ly/x2j7hpf</wslfe:stream>
		<wslfe:stream name="euronews português">https://dai.ly/x2j7lv2</wslfe:stream>
		<wslfe:stream name="Euronews Ελληνικά">https://dai.ly/x2j7kha</wslfe:stream>
		<wslfe:stream name="Euronews русски">https://dai.ly/x2j7igz</wslfe:stream>
		<wslfe:stream name="Fashion TV">http://lb.streaming.sk/fashiontv/stream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Fashion TV">http://fash1043.cloudycdn.services/slive/_definst_/ftv_paris_adaptive.smil/chunklist.m3u8</wslfe:stream>
		<wslfe:stream name="Filstalwelle">https://586c58b20c86e.streamlock.net/filstalwelle-live/_definst_/mp4:livestream/chunklist_w788671625.m3u8</wslfe:stream>
		<wslfe:stream name="Folketinget TV">https://cdnapi.kaltura.com/p/2158211/sp/327418300/playManifest/entryId/1_24gfa7qq/protocol/https/format/applehttp/a.m3u8</wslfe:stream>
		<wslfe:stream name="Formula">https://c4635.cdn.xsg.ge/c4635/TVFormula/index.m3u8</wslfe:stream>
		<wslfe:stream name="fr.euronews.com">https://rakuten-euronews-2-fr.samsung.wurl.com/manifest/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="funradio.fr/tv">https://edge20.vedge.infomaniak.com/livecast/funradiovisionhd/chunklist_w470534363.m3u8</wslfe:stream>
		<wslfe:stream name="generations.fr">https://edge19.vedge.infomaniak.com/livecast/ik:generation-tv/chunklist_w697757887.m3u8</wslfe:stream>
		<wslfe:stream name="Gospel Channel Scandinavia">https://169lawskfzaua3opl.hlscdn.obs-server.com/hls/puc9djrh2cg7wjqw8v9was5fu5kh4a.m3u8</wslfe:stream>
		<wslfe:stream name="gospel TV">http://live-h1.frontlayer.net/fl492017/live/chunks.m3u8</wslfe:stream>
		<wslfe:stream name="gott24.tv">https://jfmedien01.de:5443/LiveApp/streams/470906932351128240316939.m3u8</wslfe:stream>
		<wslfe:stream name="Greek Voice TV (wzra)">http://wpso.com:1936/hls/wzra.m3u8</wslfe:stream>
		<wslfe:stream name="GTV">http://91.220.221.60/gtv_hls/gtv_03.m3u8</wslfe:stream>
		<wslfe:stream name="HALK TV">https://halktv.blutv.com/blutv_halktv_live/live.m3u8</wslfe:stream>
		<wslfe:stream name="hellenic parliament (WebTV-1)">https://streamer-cache.grnet.gr/parliament/hls/webtv_1280_960x540/index.m3u8</wslfe:stream>
		<wslfe:stream name="hellenic parliament (WebTV-2)">https://streamer-cache.grnet.gr/parliament/hls/webtv2_1280_960x540/index.m3u8</wslfe:stream>
		<wslfe:stream name="Himlen TV 7">https://vod.tv7.fi/tv7-se/_definst_/smil:tv7-se.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Hmong TV">https://livefta.malimarcdn.com/ftaedge00/hmongusatv.sdp/chunklist.m3u8</wslfe:stream>
		<wslfe:stream name="hr-fernsehen">https://hrhls.akamaized.net/hls/live/2024525/hrhls/index.m3u8</wslfe:stream>
		<wslfe:stream name="Hunt Channel">https://1111296894.rsc.cdn77.org/LS-ATL-56868-1/index.m3u8</wslfe:stream>
		<wslfe:stream name="Ibiza Global TV">https://ibgrtv.streaming-pro.com/hls/ibgrlive.m3u8</wslfe:stream>
		<wslfe:stream name="IMPD TV">https://58a4464faef53.streamlock.net/impd/ngrp:impd_all/playlist.m3u8?PEDROJUNIORTUTORIAIS</wslfe:stream>
		<wslfe:stream name="ip tv">http://ogietv.biz.id:80/get.php?username=World&amp;password=di4mond&amp;type=m3u_plus&amp;output=mpegts</wslfe:stream>
		<wslfe:stream name="Isaac Tv Pakistan">https://livecdn.live247stream.com/isaac/tv/isaac/stream2/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Ivoire Channel">https://video1.getstreamhosting.com:1936/8244/8244/chunklist_w1227324980.m3u8</wslfe:stream>
		<wslfe:stream name="joefarm">http://iptvmedia.live:8080/get.php?username=test-b86cf0&amp;password=5a02&amp;type=m3u_plus&amp;output=ts</wslfe:stream>
		<wslfe:stream name="joj.sk">https://nn.geo.joj.sk/hls/joj-720.m3u8</wslfe:stream>
		<wslfe:stream name="Jordan HD 1080p">https://jrtv-live.ercdn.net/jordanhd/jordanhd_1080p.m3u8</wslfe:stream>
		<wslfe:stream name="Kanal 3">rtmp://stream.taksimbilisim.com/kanal3/bant1</wslfe:stream>
		<wslfe:stream name="Kazaxstan TV">rtmp://95.56.237.107:1935/live/myStream1</wslfe:stream>
		<wslfe:stream name="KidoodleTV.ca">https://kidoodletv-kdtv-1-ca.samsung.wurl.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Koha TV">rtmp://live.tvkoha.tv:1935/live/koha/livestream</wslfe:stream>
		<wslfe:stream name="Kontra TV">rtmp://flashcloud.mediacdn.com/live/kontratv</wslfe:stream>
		<wslfe:stream name="Koper TV">https://27-rtvslo-tv-kp-int.cdn.eurovisioncdn.net/playlist.m3u8?checkedby:iptvcat.com</wslfe:stream>
		<wslfe:stream name="Krone TV">https://kronetv.mdn.ors.at/out/u/kronetv-nodrm.m3u8</wslfe:stream>
		<wslfe:stream name="Kronehit TV (Austria)">https://bitcdn-kronehit.bitmovin.com/v2/hls/chunklist_b3128000.m3u8</wslfe:stream>
		<wslfe:stream name="Kurir TV">https://kurir-tv.haste-cdn.net/providus/live2805_lq/index.m3u8</wslfe:stream>
		<wslfe:stream name="La 1">https://rtvelivestreamv3.akamaized.net/rtvesec/la1/la1_main.m3u8</wslfe:stream>
		<wslfe:stream name="La 2 ES-IP">https://rtvelivestreamv3.akamaized.net/rtvesec/la2/la2_main.m3u8</wslfe:stream>
		<wslfe:stream name="LA7">https://d15umi5iaezxgx.cloudfront.net/LA7/CLN/HLS-B/Live.m3u8</wslfe:stream>
		<wslfe:stream name="Lansingerland TV">https://streaming-outbound-video-02.rtvlansingerland.nl/hls/livetv/index.m3u8</wslfe:stream>
		<wslfe:stream name="LegoChannel.us">https://legochannel-vizio.amagi.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Leo jose">https://list.iptvcat.com/my_list/s/f941a1259615aa91505e37fe249fea5c.m3u8</wslfe:stream>
		<wslfe:stream name="Life TV">https://lifetv.bitflip.ee/live/stream1_1/index.m3u8</wslfe:stream>
		<wslfe:stream name="Light Channel TV Deutschland">http://streamer1.streamhost.org:1935/salive/lctvde/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="LightChannel.ro">http://streamer1.streamhost.org:1935/salive/GMIlcbgM/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="LiveNOWfromFOX.us">https://fox-foxnewsnow-vizio.amagi.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="LocAll">http://tv.geniusnet.sk:8081/localltv/pl.m3u8</wslfe:stream>
		<wslfe:stream name="LRT">https://lituanica-dvr.lrt.lt/lrt-ndvr/hls/lituanica_720p/index.m3u8</wslfe:stream>
		<wslfe:stream name="m2o.it/tv">https://streamcdnm2-4c4b867c89244861ac216426883d1ad0.msvdn.net/live/S62628868/uhdWBlkC1AoO/chunklist_b1064000.m3u8</wslfe:stream>
		<wslfe:stream name="m6.fr">https://shls-m6-int-prod-dub.shahid.net/out/v1/a315ab77ee7343a7a17dbe7e32eee3ba/index_1.m3u8</wslfe:stream>
		<wslfe:stream name="Madha TV">http://103.109.45.5:1935/madhatv/madhatv.stream_HDp/chunklist_w1300032347.m3u8</wslfe:stream>
		<wslfe:stream name="MAVTV.us">https://mavtv-1.sinclair.wurl.com/manifest/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MAVTVSelect.us">https://mavtv-mavtvglobal-1-eu.rakuten.wurl.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MDF.1">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mdf1_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MEGA TV (GR-IP)">https://streamcdnh4-c98db5952cb54b358365984178fb898a.msvdn.net/live/S86713049/gonOwuUacAxM/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MesogeiosTV">https://e-e.cyou:8222/mesogeiostv/stream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Meteonews.ch">https://streaming.meteonews.net/hls/stream.m3u8</wslfe:stream>
		<wslfe:stream name="MMC (720p)">https://29-rtvslo-tv-mmc-int.cdn.eurovisioncdn.net/playlist.m3u8?DVR</wslfe:stream>
		<wslfe:stream name="MMC TV">https://29-rtvslo-tv-mmc-int.cdn.eurovisioncdn.net/playlist.m3u8?checkedby:iptvcat.com</wslfe:stream>
		<wslfe:stream name="Monaco Info">https://webtvmonacoinfo.mc/live/prod_720/index.m3u8</wslfe:stream>
		<wslfe:stream name="Monde du Loisir TV">http://tv.mondeduloisir.fr:1935/tixtv/smil:web.smil/chunklist_w822985751_b3555000_t64SEQ=.m3u8</wslfe:stream>
		<wslfe:stream name="MondoKids.it">https://mondotv-mondotvkids-1-it.samsung.wurl.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="mtavariarxi">https://bozztv.com/36bay2/mtavariarxi/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MuzzikHipHopSerbia.r">https://muzzik-live.morescreens.com/mts-a4/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MuzzikJekaSerbia.rs">https://muzzik-live.morescreens.com/mts-4/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MuzzikMediteraneoSer">https://muzzik-live.morescreens.com/mts-a5/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MuzzikOKKSerbia.rs">https://muzzik-live.morescreens.com/mts-2/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MuzzikRockRollSerbia">https://muzzik-live.morescreens.com/mts-1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MuzzikTVSerbia.rs">https://muzzik-live.morescreens.com/mts-6/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="MuzzikWorldwideSerbi">https://muzzik-live.morescreens.com/mts-5/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="N1 HR">https://best-str.umn.cdn.united.cloud/stream?stream=sp1400&amp;sp=n1info&amp;channel=n1hrv&amp;u=n1info&amp;p=n1Sh4redSecre7iNf0</wslfe:stream>
		<wslfe:stream name="N1 SLO">https://best-str.umn.cdn.united.cloud/stream?stream=sp1400&amp;sp=n1info&amp;channel=n1slv&amp;u=n1info&amp;p=n1Sh4redSecre7iNf0</wslfe:stream>
		<wslfe:stream name="N1 SR">https://best-str.umn.cdn.united.cloud/stream?stream=sp1400&amp;sp=n1info&amp;channel=n1srp&amp;u=n1info&amp;p=n1Sh4redSecre7iNf0</wslfe:stream>
		<wslfe:stream name="National Geographic Abu Dhabi AR ARB">https://admdn2.cdn.mangomolo.com/nagtv/smil:nagtv.stream.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="NBC News">https://nbcnews2.akamaized.net/hls/live/723426/NBCNewsPlaymaker24x7Linear99a3a827-ua/master.m3u8</wslfe:stream>
		<wslfe:stream name="nbydeggendorf.de">https://stream03.welocal.stream/stream/fhd-nbydeggendorf_99148/ngrp:stream_all/index.m3u8</wslfe:stream>
		<wslfe:stream name="nbylandshut.de">https://stream03.welocal.stream/stream/fhd-nbylandshut_75262/ngrp:stream_all/index.m3u8</wslfe:stream>
		<wslfe:stream name="NDR 1 Radio MV-VisualRadio">https://ndrvisualradiohls.akamaized.net/hls/live/2018951/ndrvr_mv_ndr1/master_540.m3u8</wslfe:stream>
		<wslfe:stream name="NDR 1 Radio MV-VisualRadio">https://ndrvisualradiohls.akamaized.net/hls/live/2018951/ndrvr_mv_ndr1/master.m3u8</wslfe:stream>
		<wslfe:stream name="NDR Hamburg HD">https://mcdn.ndr.de/ndr/hls/ndr_fs/ndr_hh/master.m3u8</wslfe:stream>
		<wslfe:stream name="NiederbayernTV.de">https://stream03.welocal.stream/stream/sat-nby/ngrp:sat-nby.stream_all/index.m3u8</wslfe:stream>
		<wslfe:stream name="NOVE ZAMKY TV">http://s1.media-planet.sk/live/novezamky/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="NOVE ZAMKY TV">rtmp://s1.media-planet.sk:80/live/novezamky</wslfe:stream>
		<wslfe:stream name="Novo Tempo RS">http://stream.novotempo.com:1935/tv/smil:TvNovoTempoCom.smil/playlist.m3u8?PEDROJUNIORTUTORIAIS</wslfe:stream>
		<wslfe:stream name="Novo Tempo SP">http://stream.novotempo.com:1935/tv/tvnovotempo.stream/playlist.m3u8?PEDROJUNIORTUTORIAIS</wslfe:stream>
		<wslfe:stream name="NRB Network [USA]">https://uni10rtmp.tulix.tv/nrbtvlive/nrbtvlive.stream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="NRWision HD">https://fms.nrwision.de/live/livestreamHD.stream_source/chunklist.m3u8</wslfe:stream>
		<wslfe:stream name="OČKO  Gold Star VLC3">https://ocko-live-dash.ssl.cdn.cra.cz/cra_live2/ocko_gold.stream.1.smil/manifest.mpd</wslfe:stream>
		<wslfe:stream name="OČKO  VLC3">https://ocko-live-dash.ssl.cdn.cra.cz/cra_live2/ocko.stream.1.smil/manifest.mpd</wslfe:stream>
		<wslfe:stream name="OČKO EXPRESS VLC3">https://ocko-live-dash.ssl.cdn.cra.cz/cra_live2/ocko_expres.stream.1.smil/manifest.mpd</wslfe:stream>
		<wslfe:stream name="Ocko.cz">https://ocko-live-dash.ssl.cdn.cra.cz/cra_live2/ocko.stream.1.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="ocko.tv/ocko-expres">https://ocko-live.ssl.cdn.cra.cz/channels/ocko_expres/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="ocko.tv/start">https://ocko-live-dash.ssl.cdn.cra.cz/cra_live2/ocko_gold.stream.1.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="oe24 TV">https://varoe24live.sf.apa.at/oe24-live1/oe24.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="oe24 TV (Austria)">http://apasfoe24l.sf.apa.at/ipad/oe24-live1/oe24.sdp/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Offener Kanal Wernigerode">https://h056.video-stream-hosting.de/medienasa-live/_definst_/ok-wernigerode_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK Dessau">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mp4:ok-dessau_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK Fulda">https://s.ok54.de/mok-fu/livestream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK Gießen">https://s.ok54.de/mok-gi/mok-gi/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK Kaiserslautern">https://s.ok54.de/abr_okkl/webstream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK Kassel">https://s.ok54.de/mok-ks/kassel/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK Kiel">https://live-cdn.oksh.de/play/hls/kieltv/index.m3u8</wslfe:stream>
		<wslfe:stream name="OK Ludwigshafen">https://s.ok54.de/oklu/livestream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK Magdeburg">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mp4:ok-magdeburg_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK Merseburg-Querfurt">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mp4:ok-merseburg_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK naheTV (Idar-Oberstein)">https://s.ok54.de/nahetv/webstream/chunks.m3u8</wslfe:stream>
		<wslfe:stream name="OK Rhein-Main (Offenbach Frankfurt)">https://s.ok54.de/mok-rm/mok-rm/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK RheinLokal (Worms)">https://s.ok54.de/rheinlokal/rheinlOKal_stream/chunks.m3u8</wslfe:stream>
		<wslfe:stream name="OK Salzwedel">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mp4:ok-salzwedel_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK Stendal">http://58bd5b7a98e04.streamlock.net/medienasa-live/_definst_/mp4:ok-stendal_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK Suedwestpfalz">https://s.ok54.de/okswp/test/chunks.m3u8</wslfe:stream>
		<wslfe:stream name="OK Weinstraße (Neustadt)">https://s.ok54.de/okweinstrasse/okweinstrasse/chunks.m3u8</wslfe:stream>
		<wslfe:stream name="OK Wernigerode">http://58bd5b7a98e04.streamlock.net/medienasa-live/_definst_/mp4:ok-wernigerode_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK4 (Adenau Andernach Koblenz Neuwied)">https://s.ok54.de/abr_ok4/live/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK4 Live">https://s.ok54.de/abr_ok4/live/ok4/live_720p/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="OK54 (Trier)">https://s.ok54.de/ott/webstream/tv/webstream_720p/chunks.m3u8</wslfe:stream>
		<wslfe:stream name="Okto (Austria)">https://cdn3.wowza.com/1/MHFtazJReW5rOFhP/N2NWNDZ2/hls/live/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Omroep Flevoland">https://d5ms27yy6exnf.cloudfront.net/live/omroepflevoland/tv/2000/prog_index.m3u8</wslfe:stream>
		<wslfe:stream name="Omroep Flevoland Radio">https://d5ms27yy6exnf.cloudfront.net/live/omroepflevoland/radio/2000/prog_index.m3u8</wslfe:stream>
		<wslfe:stream name="Omroep Gelderland Radio">https://d2od87akyl46nm.cloudfront.net/live/omroepgelderland/kijkradio/index.m3u8</wslfe:stream>
		<wslfe:stream name="omroep west">https://d2dslh4sd7yvc1.cloudfront.net/live/omroepwest/ngrp:tv-feed_all/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="one.kr.ua">https://cdn1.live-tv.cloud/1tvkr/1tvkr-abr-lq/1tvkr/1tvkr-sub/chunks.m3u8</wslfe:stream>
		<wslfe:stream name="OneNewsNetwork.us">http://oneamericanews-roku-us.amagi.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="ONETV">https://streaming.onetv.gr/show/onetv.m3u8</wslfe:stream>
		<wslfe:stream name="ORF III HD">https://orf3.mdn.ors.at/out/u/orf3/qxb/manifest.m3u8</wslfe:stream>
		<wslfe:stream name="ORF SPORT + AT-IP">https://orfs.mdn.ors.at/out/u/orfs/qxb/manifest.m3u8</wslfe:stream>
		<wslfe:stream name="OTV">https://www.dailymotion.com/video/x654gen</wslfe:stream>
		<wslfe:stream name="OutsideTVPlus.us">https://outsidetvplus-xumo.amagi.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="PalitraNews.ge">https://live.palitranews.ge/hls/palitratv/index.m3u8</wslfe:stream>
		<wslfe:stream name="Parlamentsfernsehen 2">https://cldf-hlsgw.r53.cdn.tv1.eu/1000153copo/hk2.m3u8</wslfe:stream>
		<wslfe:stream name="Pequeradio TV">https://canadaremar2.todostreaming.es/live/peque-pequetv.m3u8</wslfe:stream>
		<wslfe:stream name="PlayTV.gr">http://web.onair-radio.eu:1935/Alpha-Host/Alpha-Host/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="plus.joj.sk">https://live.cdn.joj.sk/live/hls/jojplus-540.m3u8</wslfe:stream>
		<wslfe:stream name="Polar TV">https://stream.polar.cz/polar/polarlive-1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="polar.cz">https://stream.polar.cz/polar/polarlive-2/manifest_w635624816.mpd</wslfe:stream>
		<wslfe:stream name="Preve TV">https://video01.kshost.com.br/paulispar7372/paulispar7372/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Profit">https://stream1.profit.ro:1945/profit/livestream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="PUBLIKA MD">https://livebeta.publika.md/LIVE/P/1000.m3u8</wslfe:stream>
		<wslfe:stream name="Publika TV">https://livebeta.publika.md/LIVE/P/2000.m3u8</wslfe:stream>
		<wslfe:stream name="PUNKTum">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mp4:punktum_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Qmusic.nl">https://dpp-qmusicnl-live.akamaized.net/streamx/QmusicNL.m3u8</wslfe:stream>
		<wslfe:stream name="qvc beauty uk">https://live-qvcuk.simplestreamcdn.com/live/qvcuk_main_clean/bitrate1.isml/live.m3u8</wslfe:stream>
		<wslfe:stream name="QwestTVJazzBeyond.fr">https://cdn-ue1-prod.tsv2.amagi.tv/linear/qwestAAAA-qwestjazz-uk-samsungtv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="QwestTVMix.fr">https://cdn-ue1-prod.tsv2.amagi.tv/linear/qwestAAAA-qwestmix-uk-samsungtv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="R9 (Austria)">https://ms01.w24.at/R9/smil:liveeventR9.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Radio 350">https://stream.radio350.nl/hls/radio350.m3u8</wslfe:stream>
		<wslfe:stream name="Radio S TV">https://sradio.ipradio.rs/sradio/radiostv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Rai 3">http://wzstreaming.rai.it/TVlive/liveStream/chunklist_w823540263.m3u8</wslfe:stream>
		<wslfe:stream name="Rai Südtirol">http://wzstreaming.rai.it/TVlive/liveStream/chunklist_w1379656191.m3u8</wslfe:stream>
		<wslfe:stream name="Raj TV">https://ottst05.flexitv.sk/2827-tv-pc.m3u8</wslfe:stream>
		<wslfe:stream name="RakutenFamily.fr">https://rakuten-family-7-fr.samsung.wurl.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="RakutenFamily.it">https://rakuten-family-6-it.samsung.wurl.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="RAN1">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mp4:ran1_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="RAPSODIA TV">http://92.86.248.141:8080/ram/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="RBW">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mp4:rbw_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Red TV (720p)">https://live.rednet.rs/providus/redtv_multi.m3u8</wslfe:stream>
		<wslfe:stream name="Retro TV">http://stream.mediawork.cz/retrotv//retrotvHQ1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="retromusic.cz/tv">http://stream.mediawork.cz/retrotv/retrotvHQ1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="retromusic.cz/tv">http://stream.mediawork.cz/retrotv/retrotvHQ1/chunklist_w259077935.m3u8</wslfe:stream>
		<wslfe:stream name="RFH">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mp4:RFH_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="rmtv.bg">https://transcoder1.bitcare.eu/streaming/rimextv/rmtv.m3u8</wslfe:stream>
		<wslfe:stream name="rougetv.ch">http://edge14.vedge.infomaniak.com/livecast/event.stream/chunklist_w190750142.m3u8</wslfe:stream>
		<wslfe:stream name="RTCG Sat (720p)">http://rtcg2.videostreaming.rs:1935/rtcg/rtcg.1.stream/index.m3u8</wslfe:stream>
		<wslfe:stream name="RTM plus">http://www.rtmplus.cz/live/1-playlist.m3u8</wslfe:stream>
		<wslfe:stream name="RTV (Austria)">http://iptv.rtv-ooe.at/stream.m3u8</wslfe:stream>
		<wslfe:stream name="RTV AS (576p)">https://srv1.adriatelekom.com/TVAS/index.m3u8</wslfe:stream>
		<wslfe:stream name="RTV City Ub (576p)">http://167.172.39.13/hls/tvcityub.m3u8</wslfe:stream>
		<wslfe:stream name="RTV Noord">https://media.rtvnoord.nl/live/rtvnoord/tv/index.m3u8</wslfe:stream>
		<wslfe:stream name="RTV Noord Extra">https://media.rtvnoord.nl/live/rtvnoord/extra/index.m3u8</wslfe:stream>
		<wslfe:stream name="rtvsport">https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch02/smil:ch-02.smil/master.m3u8</wslfe:stream>
		<wslfe:stream name="saarland1.de">http://saarland1.iptv-playoutcenter.de/saarland1/saarland1.stream_1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="saarland2.de">http://saarland2.iptv-playoutcenter.de/saarland2/saarland2.stream_2/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Sachsen eins">http://sachsen1.iptv-playoutcenter.de/sachsen1/sachsen1.stream_1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="sachsen-fernsehen.de">http://vogtland.iptv-playoutcenter.de/vogtland/vogtlandfernsehen.stream_1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="SALTO 1">https://olon.ctl.cdn.ebsd.ericsson.net/L8A/95f14edc/8d74cf86.isml/.m3u8</wslfe:stream>
		<wslfe:stream name="SALTO 2">https://olon.ctl.cdn.ebsd.ericsson.net/L8A/bc718ab6/65358d45.isml/.m3u8</wslfe:stream>
		<wslfe:stream name="Salto ADE TV">https://live.salto.nl/hls/at5_high.m3u8</wslfe:stream>
		<wslfe:stream name="Salto Brasa Music">https://salto-streams.nl/hls/sotv1_high.m3u8</wslfe:stream>
		<wslfe:stream name="Salto MaLive">https://live.salto.nl/hls/malive_high.m3u8</wslfe:stream>
		<wslfe:stream name="SAMIAKI TV">https://live.cast-control.eu:443/samiaki/samiaki/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="SBT (TV Jornal Caruaru)">http://evpp.mm.uol.com.br:1935/ne10/_definst_/ne10-tvjornal-caruaru-video-web.sdp/live.m3u8?IPTVCOTIA++++</wslfe:stream>
		<wslfe:stream name="SBT PE interior">http://evpp.mm.uol.com.br:1935/ne10/ne10-tvjornal-caruaru-video-web.sdp/playlist.m3u8?PEDROJUNIORTUTORIAIS</wslfe:stream>
		<wslfe:stream name="SchauTV (Austria)">https://schautv.mdn.ors.at/out/u/schautv-nodrm.m3u8</wslfe:stream>
		<wslfe:stream name="Senzi TV">http://lb.streaming.sk/senzi/stream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Severka.tv">http://88.212.7.11/live/test_severka_web_player/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="skitv.tv">https://d2xeo83q8fcni6.cloudfront.net/v1/master/9d062541f2ff39b5c0f48b743c6411d25f62fc25/SkiTV-SynapseTV/193.m3u8</wslfe:stream>
		<wslfe:stream name="SKY FOLK">http://www.skyfolk.mk/live.m3u8</wslfe:stream>
		<wslfe:stream name="Sky News Arabia">https://stream.skynewsarabia.com/hls/sna_720.m3u8</wslfe:stream>
		<wslfe:stream name="Šlagr TV">https://stream-6.mazana.tv/slagr.m3u</wslfe:stream>
		<wslfe:stream name="SLO 1">https://31-rtvslo-tv-slo1-int.cdn.eurovisioncdn.net/chunklist_b2328000_DVR.m3u8</wslfe:stream>
		<wslfe:stream name="SLO 2">https://21-rtvslo-tv-slo2-int.cdn.eurovisioncdn.net/playlist.m3u8?DVR</wslfe:stream>
		<wslfe:stream name="SLO 3">https://16-rtvslo-tv-slo3-int.cdn.eurovisioncdn.net/playlist.m3u8?DVR</wslfe:stream>
		<wslfe:stream name="Smash TV">http://a3.smashmalta.com/hls/smash/smash.m3u8</wslfe:stream>
		<wslfe:stream name="sofy.tv/de">https://sofy-ger-samsung.amagi.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Sooriyan TV">http://cdn.jwplayer.com/videos/1m0nMXhZ-3SDdwqdV.m3u8</wslfe:stream>
		<wslfe:stream name="Speranta TV">https://play.streamkit.tv/content/channel/sperantatv/live/sperantatv.player.m3u8</wslfe:stream>
		<wslfe:stream name="SportyStuffTV.uk">https://ayozat-live.secure2.footprint.net/egress/bhandler/ayozat/sportystufftv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="sr.de/sr">https://srfs.akamaized.net/hls/live/689649/srfsgeo/index.m3u8</wslfe:stream>
		<wslfe:stream name="srf.ch">https://58de7a369a9c4.streamlock.net/srf/stream_720p/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="sstv.ge">https://stream.sstv.ge/live/sstv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="STAR">https://livestar.siliconweb.com/media/star1/star1lowhd.m3u8</wslfe:stream>
		<wslfe:stream name="Star Lamia">https://dai.ly/xqjey2</wslfe:stream>
		<wslfe:stream name="Star TV">https://livestar.siliconweb.com/media/star1/star1mediumhd.m3u8</wslfe:stream>
		<wslfe:stream name="supersixtv.net">https://5db313b643fd8.streamlock.net/SUPERSIXLombardia/SUPERSIXLombardia/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="SuperTennis.it">https://supertennix-l3-live1.secure.footprint.net/restreamer/supertennix_client/gpu-a-c0-16/restreamer/rtmp/hls/h24_supertennix/manifest.m3u8</wslfe:stream>
		<wslfe:stream name="SWR3-VisualRadio">https://swrswr3vr-hls.akamaized.net/hls/live/2018683/swr3vr/master.m3u8</wslfe:stream>
		<wslfe:stream name="sylt1.tv">https://5f7f7503aa549.streamlock.net/Sylt1_Channel_1_PGM/sylt1_high/Playlist.m3u8</wslfe:stream>
		<wslfe:stream name="TA3">https://get-a-flippin-ta3-url-dss6dgprdpjf.runkit.sh/</wslfe:stream>
		<wslfe:stream name="Taevas TV7">https://vod.tv7.fi/tv7-ee/_definst_/smil:tv7-ee.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="TELE M BOTOSANI">http://89.137.197.15:8080/testing/pl5/playlist/ram/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Telemax by Diana">http://live-edge01.telecentro.net.ar/live/smil:tlx.smil/master.m3u8</wslfe:stream>
		<wslfe:stream name="Teletricolore">https://59d7d6f47d7fc.streamlock.net/rs2/rs2/chunklist_w980140357.m3u8</wslfe:stream>
		<wslfe:stream name="TG3 (TeleGiornale 3)">http://wzstreaming.rai.it/TVlive/liveStream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Thai PBS">https://thaipbs-live.cdn.byteark.com/live/playlist_1080p/index.m3u8</wslfe:stream>
		<wslfe:stream name="thevoice.bg/tv">https://bss1.neterra.tv/thevoice/stream_0.m3u8</wslfe:stream>
		<wslfe:stream name="Tide TV">https://5889e7d0d6e28.streamlock.net/tide-live/_definst_/smil:livestream.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Tisza TV">https://www.tiszatv.hu/onlinetv/tiszatv_1.m3u8</wslfe:stream>
		<wslfe:stream name="Trace Urban tv">https://lightning-traceurban-samsungau.amagi.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="trace.tv">https://lightning-traceurban-samsungau.amagi.tv/playlist720p.m3u8</wslfe:stream>
		<wslfe:stream name="Turzovka">rtmp://s1.media-planet.sk:80/live/turzovka</wslfe:stream>
		<wslfe:stream name="TV Belle Amie (720p)">http://92.60.238.10:1935/live/belleamie/chunklist_w1811501290.m3u8</wslfe:stream>
		<wslfe:stream name="TV Camara">https://stream3.camara.gov.br/tv1/manifest.m3u8</wslfe:stream>
		<wslfe:stream name="TV Duga Plus (480p)">http://109.92.29.10:1935/tvduga/tvduga/chunklist_w1097511114.m3u8</wslfe:stream>
		<wslfe:stream name="TV Hram (576p)">https://vod1.laki.eu/live/hram/index.m3u8</wslfe:stream>
		<wslfe:stream name="TV Jadran">https://www.dailymotion.com/video/x670ug8</wslfe:stream>
		<wslfe:stream name="TV Maná Brasil">https://w1.manasat.com/tvmana-brasil/smil:tvmana-brasil.smil/chunklist_w954408022_b1548000_sleng.m3u8</wslfe:stream>
		<wslfe:stream name="TV Maribor">https://24-rtvslo-tv-mb-slo.cdn.eurovisioncdn.net/playlist.m3u8?DVR</wslfe:stream>
		<wslfe:stream name="TV Nova">https://www.dailymotion.com/video/x694rtu</wslfe:stream>
		<wslfe:stream name="Tv Novi Pazar">https://rtvnp.rs/hls/rtvnp.m3u8</wslfe:stream>
		<wslfe:stream name="TV Pi Canal Pirot (576p)">http://stream.pikanal.rs/pikanal/pgm.m3u8?v=1617785340</wslfe:stream>
		<wslfe:stream name="TV Torun">http://217.173.176.107:1935/live/ngrp:tvk.stream_all/master.m3u8</wslfe:stream>
		<wslfe:stream name="TV Valkenburg">https://livestream.tvvalkenburg.tv/hls/tv-valkenburg/tv-valkenburg.m3u8</wslfe:stream>
		<wslfe:stream name="tv.traveltv.bg">https://streamer103.neterra.tv/travel/live.m3u8</wslfe:stream>
		<wslfe:stream name="TV2 Bornholm">http://live.tv2bornholm.dk/stream/live/master.m3u8</wslfe:stream>
		<wslfe:stream name="TV2Ostjylland.dk">https://cdnapisec.kaltura.com/p/2102081/sp/2102081/playManifest/entryId/0_x4p3licd/flavorIds/0_pcvatr5k,0_aezqkdsi,0_dkeq429y,0_99pivdxs/deliveryProfileId/10552/protocol/https/format/applehttp/a.m3u8</wslfe:stream>
		<wslfe:stream name="TV41 (Turkey)">rtmp://stream.taksimbilisim.com/tv41/bant1</wslfe:stream>
		<wslfe:stream name="TVDX">http://5ca49f2417d90.streamlock.net/live/dolnykubin1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="TVM 3">http://livevideo.infomaniak.com/streaming/livecast/tvm3/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="tvnatura.cz/tv">https://media1.tvnatura.cz/live_out/live.m3u8</wslfe:stream>
		<wslfe:stream name="tvNRSR (national congress)">https://n15.stv.livebox.sk/stv-tv/_definst_/stv7.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="TVP 3 Białystok">http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpbialystok</wslfe:stream>
		<wslfe:stream name="TVP 3 Bydgoszcz">http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpbydgoszcz</wslfe:stream>
		<wslfe:stream name="TVP Info">http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpinfo</wslfe:stream>
		<wslfe:stream name="TVP3 Warszawa">http://hbbtvlive.v3.tvp.pl/hbbtvlive/livestream.php?app_id=tvpwarszawa</wslfe:stream>
		<wslfe:stream name="TVT Zgorzelec">http://gargoyle.tomkow.pl/hls/tvt.m3u8</wslfe:stream>
		<wslfe:stream name="TV_Wielkopolska">https://stream6.nadaje.com:35308/live/stream-1/chunklist_w1062911391.m3u8</wslfe:stream>
		<wslfe:stream name="uctv">https://59e8e1c60a2b2.streamlock.net/509/509.stream/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="UNA TV Hrvatska (720p)">https://sdn-global-live-streaming-packager-cache.3qsdn.com/48519/48519_264_live.m3u8</wslfe:stream>
		<wslfe:stream name="UNA TV Srbija (720p)">https://sdn-global-live-streaming-packager-cache.3qsdn.com/47561/47561_264_live.m3u8</wslfe:stream>
		<wslfe:stream name="UNSERDING-VisualRadio">https://srde.akamaized.net/hls/live/2031842/visualradio-unserding/master-540p-1728.m3u8</wslfe:stream>
		<wslfe:stream name="V2Beat">https://abr.de1se01.v2beat.live/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Västmanlands Television">https://edg01-prd-se-dcs.solidtango.com/edge/_lo9yf4l5_/lo9yf4l5/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Veseljak TV">https://stream.veseljak.tv/hls/stream.m3u8</wslfe:stream>
		<wslfe:stream name="vipotv.com/argentina">http://live-edge01.telecentro.net.ar/live/smil:musictop.smil/chunklist_w1068005770_b364000_sleng.m3u8?iptvgratis?chile.m3u8</wslfe:stream>
		<wslfe:stream name="Vychodoceska TV">https://stream.polar.cz/vctv/vctvlive-1/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="W24 TV (Austria)">https://ms01.w24.at/W24/smil:liveevent.smil/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="WDR HD">https://mcdn.wdr.de/wdr/wdrfs/de/master.m3u8</wslfe:stream>
		<wslfe:stream name="Weatherspy TV">https://jukin-weatherspy-1.samsung.wurl.com/manifest/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Welt">https://welt.personalstream.tv/v1/master.m3u8</wslfe:stream>
		<wslfe:stream name="Williems Tv">rtmp://79.120.178.90:1935/williams/williamstv</wslfe:stream>
		<wslfe:stream name="Wonder">https://wonder-samsung-uk.amagi.tv/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="WTV (OK Wettin)">https://h056.video-stream-hosting.de/medienasa-live/_definst_/mp4:ok-wettin_high/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Z Zaporozhye">https://stream.ztv.zp.ua/hls/live.m3u8</wslfe:stream>
		<wslfe:stream name="ZOL TV">https://ss3.domint.net:3108/zol_str/vzol/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="Zuglo TV">https://cloudfront44.lexanetwork.com:1344/freerelay/zuglotv.sdp/playlist.m3u8</wslfe:stream>
		<wslfe:stream name="ZuidWest TV">https://live.zuidwesttv.nl/live/zwtv.m3u8</wslfe:stream>
		<wslfe:stream name="НТК">https://stream.ntktv.ua/s/ntk/ntk.m3u8</wslfe:stream>
	</wslfe:sequence>
</wslfe:webstream_link_exchange>









